apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    service: cubestore-workers
  name: cubestore-workers
spec:
  replicas: 3
  serviceName: cubestore-workers
  selector:
    matchLabels:
      service: cubestore-workers
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cubestore-workers
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUBESTORE_META_ADDR
              value: cubestore-router:9999
            - name: CUBESTORE_REMOTE_DIR
              value: /cube/data
            - name: CUBESTORE_SERVER_NAME
              value: "$(POD_NAME):10000"
              # the $(POD_NAME) is a way of referencing dependent env vars; it will resolve to "cubestore-workers-n" where n is the replica number; with 3 replicas the POD_NAMEs will be cubestore-workers-0,cubestore-workers-1, and cubestore-workers-2; these will then be needed in the CUBESTORE_WORKERS env var as an array
            - name: CUBESTORE_WORKERS
              value: cubestore-workers-0:10000,cubestore-workers-1:10000,cubestore-workers-2:10000
            - name: CUBESTORE_WORKER_PORT
              value: "10000"
          image: cubejs/cubestore:v0.28.14
          name: cubestore-workers
          ports:
            - containerPort: 10000
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
      restartPolicy: Always
      initContainers:
        - name: init-router
          image: busybox
          command: ['sh', '-c', 'until nc -vz cubestore-router:9999; do echo "Waiting for router"; sleep 2; done;']
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: cubestore-pvc
