apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cubestore-worker-1
  name: cubestore-worker-1
spec:
  ports:
    - name: "10001"
      port: 10001
      targetPort: 10001
  selector:
    io.kompose.service: cubestore-worker-1
status:
  loadBalancer: {}
