apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: cubestore-worker-2
  name: cubestore-worker-2
spec:
  ports:
    - name: "10002"
      port: 10002
      targetPort: 10002
  selector:
    service: cubestore-worker-2
status:
  loadBalancer: {}
