apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: cubestore-router
  name: cubestore-router
spec:
  replicas: 1 # MAKE SURE TO ONLY ONE 1 ROUTER AS USING MULTIPLE MIGTH CAUSE RACE CONDITIONS
  selector:
    matchLabels:
      service: cubestore-router
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cubestore-router
    spec:
      containers:
        - env:
            - name: CUBESTORE_META_PORT
              value: "9999"
            - name: CUBESTORE_REMOTE_DIR
              value: /cube/data
            - name: CUBESTORE_SERVER_NAME
              value: cubestore-router:9999
            - name: CUBESTORE_WORKERS
              value: cubestore-worker-1:10001,cubestore-worker-2:10002
          image: cubejs/cubestore:v0.28.14
          name: cubestore-router
          ports:
            - containerPort: 9999
          resources: {}
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-pv
      restartPolicy: Always
      volumes:
        - name: cubestore-pv
          persistentVolumeClaim:
            claimName: cubestore-pvc
status: {}
