apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: cubestore-workers
  name: cubestore-workers
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    service: cubestore-workers
