apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: cubestore
  name: cubestore
spec:
  replicas: 1
  selector:
    matchLabels:
      service: cubestore
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: cubestore
    spec:
      containers:
        - env:
            - name: CUBESTORE_REMOTE_DIR
              value: /cube/data
          image: cubejs/cubestore:latest
          name: cubestore
          resources: {}
          volumeMounts:
            - mountPath: /cube/data
              name: cubestore-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath: # ONLY WORKS FOR MINIKUBE OR SINGLE INSTANCE K8S CLUSTER
            path: /home/docker/conf/.cubestore
          name: cubestore-hostpath0
status: {}
