apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-router" (include "cubestore.fullname" .) }}
  labels:
    app.kubernetes.io/component: router
    {{- include "cubestore.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.router.httpPort }}
      targetPort: http
    - name: meta
      port: {{ .Values.router.metaPort }}
      targetPort: meta
    - name: mysql
      port: {{ .Values.router.mysqlPort }}
      targetPort: mysql
  selector:
    app.kubernetes.io/component: router
    {{- include "cubestore.selectorLabels" . | nindent 4 }}
