apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-master" (include "cubejs.fullname" .) }}
  labels:
    {{- include "cubejs.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: master
      {{- include "cubejs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: master
        {{- include "cubejs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: cube
          image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.global.apiPort }}
              protocol: TCP
          env:
            {{- include "cubejs.common-env" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /readyz
              port: http
          readinessProbe:
            httpGet:
              path: /livez
              port: http
          {{- if .Values.master.resources }}
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.global.volumeMounts }}
          volumeMounts:
            {{- toYaml .Values.global.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.master.affinity }}
      affinity:
        {{- toYaml .Values.master.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.master.spreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.master.spreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.global.volumes }}
      volumes:
        {{- toYaml .Values.global.volumes | nindent 8 }}
      {{- end }}
