{{- if gt (.Values.workers.workersCount | int) 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "cubestore.fullname" .) }}
  labels:
    app.kubernetes.io/component: workers
    {{- include "cubestore.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: worker
      port: {{ .Values.workers.port }}
      targetPort: worker
  selector:
    app.kubernetes.io/component: workers
    {{- include "cubestore.selectorLabels" . | nindent 4 }}
{{- end}}

